### ISSUE TITLE
Issue with generators

### ISSUE THREAD

**Issue by LostKobrakai** [crysalead/kahlan#99] opened 2015-11-04 13:47 UTC
I wanted to try out your library, but already on the fourth test I found an issue of compatibility when trying to create objects of the [\League\Period\Period](http://period.thephpleague.com/) class. 

I get the following error message: `PHP Fatal error:  Generators cannot return values using "return" …` which points to the first line of this function in the class.

```php
public function split($interval)
    {
        $startDate = $this->startDate;
        $interval = static::filterDateInterval($interval);
        do {
            $endDate = $startDate->add($interval);
            if ($endDate > $this->endDate) {
                $endDate = $this->endDate;
            }
            yield new static($startDate, $endDate);

            $startDate = $endDate;
        } while ($startDate < $this->endDate);
    }
```

It seems like some of the "money patching" functionality it using a return in the function.

**Comment by jails** [comment] 2015-11-04 13:59
Is it possible to push your complete work on a github repo so I can investigate ?

**Comment by LostKobrakai** [comment] 2015-11-04 14:14
No need for the whole project, I could make it error even with a dumped down version: https://github.com/LostKobrakai/kahlan-debug-repo

**Comment by jails** [comment] 2015-11-04 15:29
Thanks for the dumped down version :+1:
The issue is fixed in https://github.com/crysalead/kahlan/commit/285d65e98c5a96d16438e8d5790cb9af026feb77

Just remove the cached files in `tmp/kahlan` and run a `composer update` to fetch the last version of libs.

**Closed** 2015-11-04 15:29 UTC

**Comment by LostKobrakai** [comment] 2015-11-04 15:36
Great, thanks for the speedy fix.
